### ISSUE TITLE
image size problem

### ISSUE THREAD

**Issue by zmh0510** [yuke93/RL-Restore#1]
hello, it is a wonderful project! But i am wondering that i must input a fixed image to the project? say 63*63? How can i input a 600*480 image to the project? thanks a lot !

**Comment by zmh0510** [comment]
OK！looking forward to it, especially the training code!

**Comment by hernan3009** [comment]
@yuke93 It looks very interesting. Before see this issue I think in the following simple idea:

1 - Generate many patches sharing (in some way) common pixels. 
I thought in something like: If a patch cover a 63*63 pixel square from ` (x_0,y_0)` to `(x_0+62,y_0+62)`, the next horizontal patch going from `(x_0+31,y_0+31)` to `(x_0+31+62,y_0+31+62)` ...  And something analogous for the `y` coordinate.
2 - Then reconstruct the image using some kind of interpolation. For example, weighting the patch contribution depending on the distance to the patch center.

In your experience, do you think that this could work? If it is plausible, how can I choose "the best" output image for the patch? I see in the output something like:

`mano_in_11_13_13.png  mano_in_11_13.png  mano_in_11.png`
`8_in_5_11_13.png  8_in_5_11.png  8_in_5.png`

but I am unsure about the naming convention.

Regards

**Comment by yuke93** [comment]
Hi @hernan3009 ,

I have tried some similar interpolation approaches as you said but the results are sometimes not pleasant because there is not any constraint about the selected toolchains between adjacent patches. When the selected toolchains are different, the interpolated image might look strange, and the PSNR is not as good as the voting method as I described above.

The number after '_in_' stands for the indices of sequentially selected tools. Please see the table below:

| Index | Distortion Type | Distortion Level Interval |
| :----: | :---------------: | :------------------------: |
|  1      |  Gaussian blur | [0, 1.25] |
|  2      |  Gaussian blur | [1.25, 2.5] |
|  3      |  Gaussian blur | [2.5, 3.75] |
|  4      |  Gaussian blur | [3.75, 5] |
|  5      |  Gaussian noise | [0, 12.5] |
|  6      |  Gaussian noise | [12.5, 25] |
|  7      |  Gaussian noise | [25, 37.5] |
|  8      |  Gaussian noise | [37.5, 50] |
|  9      |  JPEG compression | [60, 100] |
|  10     |  JPEG compression | [35, 60] |
|  11     |  JPEG compression | [20, 35] |
|  12     |  JPEG compression | [10, 20] |
|  13     |  None | N/A |

**Comment by lvzhengyi0204** [comment]
Hello, it is a exciting work, I want to know whether the test stage have the ability of arbitrary size input.
In the code, I don't see the related features. I am looking forward to your reply.

**Comment by yuke93** [comment]
Hi @lvzhengyi0204,

I haven't added this feature yet. I will implement the heuristic method, as discussed above, to support arbitrary size input, by the end of this week.

**Comment by yuke93** [comment]
Dear all,

Thanks for your advice and comments. Now we support arbitrary input size while inference. Put your images in `data/test/mine/` and then run
```
python main.py --dataset mine
```

**Comment by hernan3009** [comment]
Thank you! Works here under Python3.

**Comment by lvzhengyi0204** [comment]
Thank you very much！ It helps a lot for my research work.

**Comment by yuke93** [comment]
I am very glad that you like it :smiley:

**Comment by s-sanyal** [comment]
I really liked this project. I recently faced an issue while using this project in Google Colab. `absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from /content/RL-Restore/main.py.  Description from first occurrence: directory to write logfiles into
`
Could you please explain how to get rid of this issue. Thanks in advance :) @yuke93

**Comment by JialinKang** [comment]
> I really liked this project. I recently faced an issue while using this project in Google Colab. `absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from /content/RL-Restore/main.py. Description from first occurrence: directory to write logfiles into `
> Could you please explain how to get rid of this issue. Thanks in advance :) @yuke93

I also have the same question, hope to get a reply! Thanks a lot!
