### ISSUE TITLE
How to get the same value of PSNR in paper

### ISSUE THREAD

**Issue by axiniu** [yuke93/RL-Restore#6]
Hi Yue
Thanks for your paper and code.
I have implemented the code you published successfully,but I just get a value  27.1 of PSNA lower than you mentioned 28 in paper. Can you tell me more details in the training process.Thanks.

**Comment by yuke93** [comment]
Hi @axiniu ,

I believe you are asking about the performance on the "Mild" test set. When training the agent, we not only use data with mixed distortions, but also adopt some data for training the tools (the proportion is about 1:1). The reason is that all baseline models observe the data for training tools, and this indeed helps improve the performance on "Mild" test set. Also, using joint training will improve another 0.2 dB.

**Comment by axiniu** [comment]
thank you.I will have another try.

**Comment by Lixueqingqq** [comment]
Hi Yue
I'm confused about how to conduct joint training，the tools seem to have been trained in advance. when I run the train code I didn't find the part for tool training and the models of tools didn't update. Can you tell me more details about that.Thanks.

**Comment by yuke93** [comment]
Hi @Lixueqingqq,

You are right. The codes are used for training the agent. I have not released the codes for joint training, which I just naively implement following the Algorithm 1 in the paper.
